const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const {syncIosNodeEnvironment} = require('../src/ios-node-env');
const {ensureIosPods} = require('../src/ios');

function fixture(t, content) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'onramp-ios-node-'));
  t.after(() => fs.rmSync(root, {recursive: true, force: true}));
  const file = path.join(root, '.xcode.env.local');
  if (content !== undefined) fs.writeFileSync(file, content);
  return {root, file};
}

test('repairs stale literal Xcode Node pins while preserving other settings and comments', t => {
  for (const assignment of [
    'export NODE_BINARY=/old/node',
    'export NODE_BINARY="/old path/node"',
    "export NODE_BINARY='/old path/node'",
    'export NODE_BINARY=/old\\ path/node',
    'NODE_BINARY=node',
  ]) {
    const {root, file} = fixture(t, `# local settings\n${assignment} # generated by CocoaPods\nexport OTHER_SETTING=kept\n`);
    assert.equal(syncIosNodeEnvironment(root, '/selected/node').changed, true);
    const updated = fs.readFileSync(file, 'utf8');
    assert.ok(updated.includes("NODE_BINARY='/selected/node' # generated by CocoaPods"));
    assert.ok(updated.startsWith('# local settings\n'));
    assert.ok(updated.endsWith('export OTHER_SETTING=kept\n'));
    const modified = fs.statSync(file).mtimeMs;
    assert.equal(syncIosNodeEnvironment(root, '/selected/node').changed, false);
    assert.equal(fs.statSync(file).mtimeMs, modified);
  }
});

test('preserves dynamic and ambiguous custom Xcode resolvers without executing them', t => {
  for (const assignment of [
    'export NODE_BINARY=$(command -v node)',
    'export NODE_BINARY="$MY_NODE_BINARY"',
    'export NODE_BINARY=`custom-resolver`',
    'export NODE_BINARY=/custom/node && do-something',
    'export NODE_BINARY=/old/node\nexport NODE_BINARY="${NODE_OVERRIDE:-node}"',
    'if test -n "$CUSTOM_NODE"; then export NODE_BINARY="$CUSTOM_NODE"; fi',
    'readonly NODE_BINARY=/custom/node',
  ]) {
    const content = `${assignment}\nexport OTHER_SETTING=kept\n`;
    const {root, file} = fixture(t, content);
    assert.deepEqual(syncIosNodeEnvironment(root, '/selected/node'), {changed: false, preservedCustom: true});
    assert.equal(fs.readFileSync(file, 'utf8'), content);
  }
});

test('creates missing Xcode Node pins and appends without dropping unrelated settings', t => {
  for (const content of [undefined, '# local config\r\nexport OTHER=1\r\n', 'export OTHER=1']) {
    const {root, file} = fixture(t, content);
    assert.equal(syncIosNodeEnvironment(root, "/selected/Node's folder/node").changed, true);
    const updated = fs.readFileSync(file, 'utf8');
    if (content) assert.ok(updated.startsWith(content));
    assert.ok(updated.includes("export NODE_BINARY='/selected/Node'\\''s folder/node'"));
    if (content?.includes('\r\n')) assert.equal(updated.replaceAll('\r\n', '').includes('\n'), false);
    assert.deepEqual(syncIosNodeEnvironment(root, "/selected/Node's folder/node"), {changed: false, preservedCustom: false});
  }
});

test('does not follow linked local Xcode configuration or accept executable-path injection', t => {
  const {root, file} = fixture(t);
  assert.throws(() => syncIosNodeEnvironment(root, '/node\nmalicious-command'), /single-line/);
  assert.throws(() => syncIosNodeEnvironment(root, 'relative-node'), /absolute/);
  if (process.platform === 'win32') return;
  const target = path.join(root, 'shared.env');
  fs.writeFileSync(target, 'export NODE_BINARY=/old/node\n');
  fs.symlinkSync(target, file);
  assert.deepEqual(syncIosNodeEnvironment(root, '/selected/node'), {changed: false, preservedCustom: true});
  assert.equal(fs.readFileSync(target, 'utf8'), 'export NODE_BINARY=/old/node\n');
  fs.renameSync(target, path.join(root, 'saved.env'));
  assert.deepEqual(syncIosNodeEnvironment(root, '/selected/node'), {changed: false, preservedCustom: true});
  assert.equal(fs.existsSync(target), false);
  assert.equal(fs.lstatSync(file).isSymbolicLink(), true);
});

test('refreshes the Node pin even when the CocoaPods lockfiles are already current', t => {
  const {root, file} = fixture(t, 'export NODE_BINARY=/old/node\n');
  const podsProject = path.join(root, 'Pods', 'Pods.xcodeproj', 'project.pbxproj');
  fs.mkdirSync(path.dirname(podsProject), {recursive: true});
  fs.writeFileSync(podsProject, 'IPHONEOS_DEPLOYMENT_TARGET = 13.0;\n');
  const helpers = path.join(
    root,
    'node_modules',
    'react-native',
    'scripts',
    'cocoapods',
    'helpers.rb',
  );
  fs.mkdirSync(path.dirname(helpers), {recursive: true});
  fs.writeFileSync(
    helpers,
    "def self.min_ios_version_supported\n  return '15.1'\nend\n",
  );
  fs.writeFileSync(path.join(root, 'Podfile.lock'), 'LOCKED');
  fs.writeFileSync(path.join(root, 'Pods', 'Manifest.lock'), 'LOCKED');
  ensureIosPods(root, {env: {}, xcrun: '/missing/xcrun'}, {outputDir: root});
  assert.ok(fs.readFileSync(file, 'utf8').includes(process.execPath));
  assert.match(fs.readFileSync(podsProject, 'utf8'), /DEPLOYMENT_TARGET = 15\.1/);
});
